#!/bin/bash

# List the difference between PHP INI versions

if [[ $# -lt 2 || $# -gt 3 || ( $# -eq 3 && ( $3 != "cli" && $3 != "apache2" && $3 != "cgi" && $3 != "cli" && $3 != "fpm" ) )  ]]; then echo "Usage: $0 VERSIONS [apache2|cgi|cli|fpm]"; exit 1; fi

ver1="$1"
ver2="$2"
install="$3"

if [[ $# -eq 2 ]]; then install="cli"; fi

for x in $ver1 $ver2; do
        ini="/etc/php/${install}-php${x}/php.ini"
        if [[ ! -e "/etc/php/${install}-php${x}/php.ini" ]]; then echo "Could not for $ini"; exit 1; fi
done

diff -y --suppress-common-lines <(egrep -v "(^(;|\[|$))" /etc/php/${install}-php${ver1}/php.ini) <(egrep -v "(^(;|\[|$))" /etc/php/${install}-php${ver2}/php.ini)
